<?php

// Routing options
function cipher_menu() {
    $items['cipher'] = [
        'title' => 'Cipher a phrase',
        'page callback' => 'drupal_get_form',
        'page arguments' => ['cipher_form'],
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    ];
    $items['cipher_answer_page'] = [
        'title' => 'Your Encrypted Phrase',
        'page callback' => 'cipher_answer',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    ];
    return $items;
}

// Create form
function cipher_form() {
    $form['cipher_shift_value'] = [
        '#title' => 'Enter shift value:',
        '#type' => 'textfield',
        '#description' => t('Number of places you want to shift each letter.'),
        '#element_validate' => ['element_validate_integer_positive', 'letter_range'],
        '#required' => TRUE,
    ];
    $form['cipher_direction'] = [
        '#title' => 'Enter direction (left or right):',
        '#type' => 'textfield',
        '#description' => t("Will shift letters 'left' or 'right'."),
        '#element_validate' => ['check_direction'],
        '#required' => TRUE,
    ];
    $form['cipher_phrase'] = [
        '#title' => 'Enter phrase:',
        '#type' => 'textfield',
        '#description' => t("The phrase you to encrypt."),
        '#required' => TRUE,
    ];
    $form['submit'] = [
        '#type' => 'submit',
        '#value' => 'Encrypt',
    ];
    return $form;
}

// Vaildation
function letter_range($element) {
    if($element['#value'] < 1 || $element['#value'] > 26){
    form_error($element, t('The number must be between 1 and 26 (letters in the alphabet).'));
    }
}

function check_direction($element) {
    if (!($element['#value'] == 'right' || $element['#value'] == 'left')) {
        form_error($element, t("Please enter 'left' or 'right' direction."));
    }
}

// Compare and submit
function cipher_form_submit($form, &$form_state) {
    // Get user input values
    $cipher_shift_value = $form_state['values']['cipher_shift_value'];
    $cipher_direction = strtolower($form_state['values']['cipher_direction']);
    $cipher_phrase = strtolower($form_state['values']['cipher_phrase']);
    // Get string length for loop
    $phrase_len = strlen($cipher_phrase);
    $output = '';

    for ($i=0; $i < $phrase_len; $i++) {
        // Find ASCII index of letter and return only one letter
       $letter = ord(substr($cipher_phrase ,$i, 1));
       // If letter index is > 96 and < 123
       if ($letter > 96 && $letter < 123) {
           // If user direction is 'left'
           if ($cipher_direction == 'left') {
               // Subtract 97 from letter index
               $letter = $letter - 97;
               // Apply shift value to determine new index position
               $letter = ($letter + (26 - $cipher_shift_value)) % 26 + 97;
           }
           // If user direction is 'right'
           if ($cipher_direction == 'right') {
               // Subtract 97 from letter index
               $letter = $letter - 97;
               // Apply shift value to determine new index position
               $letter = ($letter + $cipher_shift_value) % 26 + 97;
           }
       }
       // Change index back into ASCII value
       $output .= chr($letter);
   }
    // Store session data
    $_SESSION['answer'] = $output;
    // Display answer on new page when form is submitted
    $form_state['redirect'] = 'cipher_answer_page';
}

// Display on answer page
function cipher_answer() {
    // Pull in session data
    $phrase = $_SESSION['answer'];
    // Display encrypted phrase
    return "<h2><strong>$phrase</strong> is your new secret message!</h2>";
}
