<?php

function cipher_menu() {
    $items['cipher'] = [
        'title' => 'Cipher a phrase',
        'page callback' => 'drupal_get_form',
        'page arguments' => ['cipher_form'],
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    ];
    $items['cipher_answer_page'] = [
        'title' => 'Your Encrypted Phrase!',
        'page callback' => 'cipher_answer',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    ];
    return $items;
}

function cipher_form() {
    $form['cipher_shift_value'] = [
        '#title' => 'Enter shift value:',
        '#type' => 'textfield',
        '#description' => 'Number of places you want to shift each letter.',
        '#element_validate' => [],
    ];
    $form['cipher_direction'] = [
        '#title' => 'Enter direction (left or right):',
        '#type' => 'textfield',
        '#description' => "Will shift letters 'left' or 'right'.",
    ];
    $form['cipher_phrase'] = [
        '#title' => 'Enter phrase:',
        '#type' => 'textfield',
        '#description' => "The phrase you to encrypt.",
    ];
    $form['submit'] = [
        '#type' => 'submit',
        '#value' => 'Encrypt',
    ];
    return $form;
}

function cipher_form_submit($form, &$form_state) {
    $cipher_shift_value = $form_state['values']['cipher_shift_value'];
    $cipher_direction = $form_state['values']['cipher_direction'];
    $cipher_phrase = $form_state['values']['cipher_phrase'];
    $answers = [$cipher_shift_value, $cipher_direction];
    $_SESSION['answers_output'] = $answers;
    $form_state['redirect'] = 'cipher_answer_page';
}

function cipher_answer() {

}
